/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.asharia.cybercafe;

import com.asharia.cybercafe.entity.Computer;
import com.formdev.flatlaf.FlatLightLaf;

import javax.swing.table.DefaultTableModel;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author Nytri
 */
public class Dashboard extends javax.swing.JFrame {

    private final Server server = new Server();

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        server.startServer();
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu_powerOptions = new javax.swing.JPopupMenu();
        menuItem_shutdownPC = new javax.swing.JMenuItem();
        menuItem_restartPC = new javax.swing.JMenuItem();
        menuItem_sleepPC = new javax.swing.JMenuItem();
        container = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        computerTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnPopup_poweroption = new javax.swing.JButton();
        btn_refreshTable = new javax.swing.JButton();
        btn_setTimer = new javax.swing.JButton();
        txt_timer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_sendMessage = new javax.swing.JTextArea();
        btn_sendMessage = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();

        menuItem_shutdownPC.setText("Shutdown Selected PC");
        menuItem_shutdownPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_shutdownPCActionPerformed(evt);
            }
        });
        popupMenu_powerOptions.add(menuItem_shutdownPC);

        menuItem_restartPC.setText("Reboot Selected PC");
        menuItem_restartPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_restartPCActionPerformed(evt);
            }
        });
        popupMenu_powerOptions.add(menuItem_restartPC);

        menuItem_sleepPC.setText("Sleep Selected PC");
        menuItem_sleepPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_sleepPCActionPerformed(evt);
            }
        });
        popupMenu_powerOptions.add(menuItem_sleepPC);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(255, 255, 255));

        computerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Computer name", "Computer OS", "Time to be finished", "Is currently use?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPane.setViewportView(computerTable);
        if (computerTable.getColumnModel().getColumnCount() > 0) {
            computerTable.getColumnModel().getColumn(0).setResizable(false);
            computerTable.getColumnModel().getColumn(1).setResizable(false);
            computerTable.getColumnModel().getColumn(2).setResizable(false);
            computerTable.getColumnModel().getColumn(3).setResizable(false);
        }

        btnPopup_poweroption.setText("Power options");
        btnPopup_poweroption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPopup_poweroptionMouseClicked(evt);
            }
        });

        btn_refreshTable.setText("Refresh");
        btn_refreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshTableActionPerformed(evt);
            }
        });

        btn_setTimer.setText("Set");
        btn_setTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setTimerActionPerformed(evt);
            }
        });

        txt_timer.setToolTipText("Set timer by minutes");

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Set Computer Timer:");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Send Message:");

        textArea_sendMessage.setColumns(20);
        textArea_sendMessage.setRows(5);
        jScrollPane1.setViewportView(textArea_sendMessage);

        btn_sendMessage.setText("Send");
        btn_sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendMessageActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_setTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_timer, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_refreshTable, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPopup_poweroption)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sendMessage)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_timer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_setTimer))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sendMessage)
                            .addComponent(btn_reset))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_refreshTable, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPopup_poweroption, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshTableActionPerformed
        refreshComputerTable();
    }//GEN-LAST:event_btn_refreshTableActionPerformed

    private void btn_sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sendMessageActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btnPopup_poweroptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPopup_poweroptionMouseClicked
        popupMenu_powerOptions.show(btnPopup_poweroption, btnPopup_poweroption.getWidth() /2, btnPopup_poweroption.getHeight() / 2);
    }//GEN-LAST:event_btnPopup_poweroptionMouseClicked

    private void btn_setTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setTimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_setTimerActionPerformed

    private void menuItem_shutdownPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_shutdownPCActionPerformed
        String IPv4 = computerTable.getValueAt(computerTable.getSelectedRow(), 2).toString();
        server.sendPowerSignal(IPv4, "shutdown");
    }//GEN-LAST:event_menuItem_shutdownPCActionPerformed

    private void menuItem_restartPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_restartPCActionPerformed
        String IPv4 = computerTable.getValueAt(computerTable.getSelectedRow(), 2).toString();
        server.sendPowerSignal(IPv4, "reboot");
    }//GEN-LAST:event_menuItem_restartPCActionPerformed

    private void menuItem_sleepPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_sleepPCActionPerformed
        String IPv4 = computerTable.getValueAt(computerTable.getSelectedRow(), 2).toString();
        server.sendPowerSignal(IPv4, "sleep");
    }//GEN-LAST:event_menuItem_sleepPCActionPerformed

    public static void refreshComputerTable() {
        DefaultTableModel computerTableModel = (DefaultTableModel) computerTable.getModel();
        computerTableModel.setRowCount(0);

        Server.computers.forEach(computer -> {
            computerTableModel.addRow(new String[]{ computer.getComputerName(), computer.getComputerOS(), computer.getComputerLocalIP(), (computer.isComputerIsBeingUse() ? "Not available" : "Available")});
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPopup_poweroption;
    private javax.swing.JButton btn_refreshTable;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sendMessage;
    private javax.swing.JButton btn_setTimer;
    public static javax.swing.JTable computerTable;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuItem_restartPC;
    private javax.swing.JMenuItem menuItem_shutdownPC;
    private javax.swing.JMenuItem menuItem_sleepPC;
    private javax.swing.JPopupMenu popupMenu_powerOptions;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTextArea textArea_sendMessage;
    private javax.swing.JTextField txt_timer;
    // End of variables declaration//GEN-END:variables
}
